/*
 
 */
package swing;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * Team Hackercode
 *
 */
public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
        setLocationRelativeTo(this);
        homePanel.setVisible(true);
        studentPanel.setVisible(false);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
        addStudentPanel.setVisible(false);

        showDate();
        showTime();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        homeLabel = new javax.swing.JPanel();
        homeButton = new javax.swing.JLabel();
        inventoryLabel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        studentLabel = new javax.swing.JPanel();
        studentButton = new javax.swing.JLabel();
        staffLabel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        attendenceLabel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        timingLabel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        accountLabel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        menuPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        studentPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        canvas2 = new java.awt.Canvas();
        addStudentButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        addStudentPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        fatherNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        collegeLabel = new javax.swing.JLabel();
        feeStatusLabel = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        fatherName = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        college = new javax.swing.JTextField();
        feestatus = new javax.swing.JTextField();
        addStudentButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        staffPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        canvas3 = new java.awt.Canvas();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        inventoryPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        canvas4 = new java.awt.Canvas();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        timingsPanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        canvas7 = new java.awt.Canvas();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        attendencePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        canvas9 = new java.awt.Canvas();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        accountPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        canvas5 = new java.awt.Canvas();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        canvas6 = new java.awt.Canvas();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel.setBackground(new java.awt.Color(23, 35, 51));
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeLabelMousePressed(evt);
            }
        });

        homeButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");

        javax.swing.GroupLayout homeLabelLayout = new javax.swing.GroupLayout(homeLabel);
        homeLabel.setLayout(homeLabelLayout);
        homeLabelLayout.setHorizontalGroup(
            homeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        homeLabelLayout.setVerticalGroup(
            homeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 70));

        inventoryLabel.setBackground(new java.awt.Color(23, 35, 51));
        inventoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inventoryLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inventoryLabelMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Inventory");

        javax.swing.GroupLayout inventoryLabelLayout = new javax.swing.GroupLayout(inventoryLabel);
        inventoryLabel.setLayout(inventoryLabelLayout);
        inventoryLabelLayout.setHorizontalGroup(
            inventoryLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryLabelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        inventoryLabelLayout.setVerticalGroup(
            inventoryLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        side_pane.add(inventoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 70));

        studentLabel.setBackground(new java.awt.Color(23, 35, 51));
        studentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentLabelMousePressed(evt);
            }
        });

        studentButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentButton.setForeground(new java.awt.Color(255, 255, 255));
        studentButton.setText("Student ");
        studentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout studentLabelLayout = new javax.swing.GroupLayout(studentLabel);
        studentLabel.setLayout(studentLabelLayout);
        studentLabelLayout.setHorizontalGroup(
            studentLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentButton)
                .addGap(142, 142, 142))
        );
        studentLabelLayout.setVerticalGroup(
            studentLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        side_pane.add(studentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 70));

        staffLabel.setBackground(new java.awt.Color(23, 35, 51));
        staffLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffLabelMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Staff");

        javax.swing.GroupLayout staffLabelLayout = new javax.swing.GroupLayout(staffLabel);
        staffLabel.setLayout(staffLabelLayout);
        staffLabelLayout.setHorizontalGroup(
            staffLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffLabelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );
        staffLabelLayout.setVerticalGroup(
            staffLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        side_pane.add(staffLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 60));

        attendenceLabel.setBackground(new java.awt.Color(23, 35, 51));
        attendenceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attendenceLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                attendenceLabelMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Attendence");

        javax.swing.GroupLayout attendenceLabelLayout = new javax.swing.GroupLayout(attendenceLabel);
        attendenceLabel.setLayout(attendenceLabelLayout);
        attendenceLabelLayout.setHorizontalGroup(
            attendenceLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendenceLabelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        attendenceLabelLayout.setVerticalGroup(
            attendenceLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        side_pane.add(attendenceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, 70));

        timingLabel.setBackground(new java.awt.Color(23, 35, 51));
        timingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timingLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                timingLabelMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Timing");

        javax.swing.GroupLayout timingLabelLayout = new javax.swing.GroupLayout(timingLabel);
        timingLabel.setLayout(timingLabelLayout);
        timingLabelLayout.setHorizontalGroup(
            timingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timingLabelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        timingLabelLayout.setVerticalGroup(
            timingLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        side_pane.add(timingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 70));

        accountLabel.setBackground(new java.awt.Color(23, 35, 51));
        accountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountLabelMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Account");

        javax.swing.GroupLayout accountLabelLayout = new javax.swing.GroupLayout(accountLabel);
        accountLabel.setLayout(accountLabelLayout);
        accountLabelLayout.setHorizontalGroup(
            accountLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLabelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        accountLabelLayout.setVerticalGroup(
            accountLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        side_pane.add(accountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 70));

        menuPanel1.setBackground(new java.awt.Color(23, 35, 51));
        menuPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPanel1MousePressed(evt);
                menulabelmousepressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuPanel1MouseReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Menu");

        javax.swing.GroupLayout menuPanel1Layout = new javax.swing.GroupLayout(menuPanel1);
        menuPanel1.setLayout(menuPanel1Layout);
        menuPanel1Layout.setHorizontalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        menuPanel1Layout.setVerticalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        side_pane.add(menuPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 200, 70));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 760));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Delete_26px_4.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MESS MANAGEMENT");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Subtract_26px_2.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exit)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1040, 50));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Home");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 0, 122, 60));

        homePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 60));

        dateLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        dateLabel.setText("todaysDate");
        homePanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 200, 60));
        homePanel.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Menu");
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel22.setText("Date :");
        homePanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 100, 60));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel23.setText("Time :");
        homePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 110, 60));

        timeLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        timeLabel.setText("currentTime");
        homePanel.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 220, 60));

        jTable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Monday", "Poha, Jalebi", "Pav Bhaji", "Dosa"},
                {"Tuesday", "poha, samosa", "Roti Sabji", "Dal Chawal"},
                {"Wednesday", "chowmeeen", "Idli Sambar", "Continental"},
                {"Thursday", "Khaman", "Aloo ke paranthe", "Mutter"},
                {"Friday", "Poha, Jalebi", "Pav Bhaji", "Dosa"},
                {"Saturday", "samosa", "Sabji", "Chawal"},
                {"Sunday", "chowmeeen", "Sambar", null}
            },
            new String [] {
                "Day", "Breakfast", "Lunch", "Dinner"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        homePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 930, 200));

        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1030, 730));

        studentPanel.setBackground(new java.awt.Color(255, 255, 255));
        studentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Student");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 0, 258, 60));

        studentPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 60));
        studentPanel.add(canvas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        studentPanel.add(addStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 110, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("120");
        studentPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 190, 50));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setText("Total Student Registered :");
        studentPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 250, 50));

        searchTextField.setToolTipText("Search here\n\n");
        studentPanel.add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, 30));

        jButton1.setText("Fees Details");
        studentPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 110, 50));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Search");
        studentPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        getContentPane().add(studentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1040, 720));

        addStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firstNameLabel.setText("First Name :");
        addStudentPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 78, 120, -1));

        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lastNameLabel.setText("Last Name :");
        addStudentPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 119, 120, -1));

        contactLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        contactLabel.setText("Contact :");
        addStudentPanel.add(contactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 201, -1, -1));

        fatherNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fatherNameLabel.setText("Father's Name :");
        addStudentPanel.add(fatherNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        addressLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addressLabel.setText("Address :");
        addStudentPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 242, 120, -1));

        collegeLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        collegeLabel.setText("College :");
        addStudentPanel.add(collegeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 283, 120, -1));

        feeStatusLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        feeStatusLabel.setText("Fee Status :");
        addStudentPanel.add(feeStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 324, 120, -1));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        addStudentPanel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 82, 215, -1));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        addStudentPanel.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 123, 215, -1));

        fatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherNameActionPerformed(evt);
            }
        });
        addStudentPanel.add(fatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 164, 215, -1));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        addStudentPanel.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 205, 215, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        addStudentPanel.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 246, 215, -1));

        college.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeActionPerformed(evt);
            }
        });
        addStudentPanel.add(college, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 287, 215, -1));

        feestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feestatusActionPerformed(evt);
            }
        });
        addStudentPanel.add(feestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 328, 215, -1));

        addStudentButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addStudentButton1.setText("Add");
        addStudentButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentButton1MouseClicked(evt);
            }
        });
        addStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButton1ActionPerformed(evt);
            }
        });
        addStudentPanel.add(addStudentButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 421, 90, 35));

        jPanel9.setBackground(new java.awt.Color(0, 153, 255));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setText("Add Student");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(405, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addStudentPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 40));

        getContentPane().add(addStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1040, 660));

        staffPanel.setBackground(new java.awt.Color(255, 255, 255));
        staffPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Staff");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        staffPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));
        staffPanel.add(canvas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icon.jpg"))); // NOI18N
        staffPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel32.setText("Ramesh");
        staffPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icon.jpg"))); // NOI18N
        staffPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setText("Suresh");
        staffPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, 30));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setText("Bunty");
        staffPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, 30));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icon.jpg"))); // NOI18N
        staffPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icon.jpg"))); // NOI18N
        staffPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icon.jpg"))); // NOI18N
        staffPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icon.jpg"))); // NOI18N
        staffPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setText("Ramu Kaka");
        staffPanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 630, -1, 30));

        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setText("Ritesh");
        staffPanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, 30));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setText("Hemant");
        staffPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, -1, 30));

        getContentPane().add(staffPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1030, 730));

        inventoryPanel.setBackground(new java.awt.Color(255, 255, 255));
        inventoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText(" Inventory Details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inventoryPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));
        inventoryPanel.add(canvas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jTable2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tomato", "25 kg"},
                {"Cabbage", "20 kg"},
                {"Maida", "20 kg"},
                {"Sugar", "25 kg"},
                {"Turmeric", "4 kg"},
                {"Coriander", "----Required-----"},
                {"Milk", "5 Litre (Warning)"},
                {"Apple", "4 kg"},
                {"Banana", "3 kg"}
            },
            new String [] {
                "Items", "Quantity"
            }
        ));
        jTable2.setRowHeight(30);
        jScrollPane2.setViewportView(jTable2);

        inventoryPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 930, 340));

        getContentPane().add(inventoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1030, 730));

        timingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        timingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setText("Timings ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        timingsPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel17.setText("Date : 17.02.19");
        timingsPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 290, 60));
        timingsPanel.add(canvas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel25.setText("Dinner : 7:00 pm to 9.30 pm");
        timingsPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 640, 50));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel26.setText("Breakfast : 7:30 am to 9.30 am");
        timingsPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 640, 50));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel27.setText("Lunch : 12:00 am to 3 pm");
        timingsPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 640, 50));

        getContentPane().add(timingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1030, 730));

        attendencePanel.setBackground(new java.awt.Color(255, 255, 255));
        attendencePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("Attendance");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        attendencePanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));
        attendencePanel.add(canvas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jTable4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"101", "Ravi", "P", "P", "P"},
                {"102", "Kishan", "A", "P", "P"},
                {"103", "Raju", "P", "A", "A"},
                {"104", "Bunty", "P", "P", "A"},
                {"105", "Babli", "P", "P", "P"},
                {"106", "Pratik", "A", "A", "A"},
                {"107", "Sahu", "P", "P", "A"},
                {"108", "Virat", "P", "P", "P"},
                {"109", "Sarthak", "A", "A", "A"},
                {"110", "Vimal", "P", "P", "P"},
                {"111", "Suresh", "P", "P", "P"},
                {"112", "Ramesh", "A", "A", "A"},
                {"113", "Ragini", "A", "P", "P"},
                {"114", "Kamal", "P", "P", "P"},
                {"115", "Priya", "P", "P", "P"},
                {"116", "Payal", "A", "A", null}
            },
            new String [] {
                "StudentID", "Name", "Breakfast", "Lunch", "Dinner"
            }
        ));
        jTable4.setRowHeight(25);
        jScrollPane4.setViewportView(jTable4);

        attendencePanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 930, 300));

        getContentPane().add(attendencePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1030, 730));

        accountPanel.setBackground(new java.awt.Color(255, 255, 255));
        accountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Account");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        accountPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));
        accountPanel.add(canvas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel29.setText("Current Username :");
        accountPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        accountPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 310, 40));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel31.setText("Current Password :");
        accountPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        accountPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 310, 40));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel43.setText("New Username :");
        accountPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        accountPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 310, 40));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        accountPanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 310, 40));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel44.setText("New Password :");
        accountPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setText("Update Details");
        accountPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 531, 200, 40));

        getContentPane().add(accountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1030, 730));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("Menu");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));
        menuPanel.add(canvas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jTable3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Monday", "Poha, Jalebi", "Pav Bhaji", "Dosa"},
                {"Tuesday", "poha, samosa", "Roti Sabji", "Dal Chawal"},
                {"Wednesday", "chowmeeen", "Idli Sambar", "Continental"},
                {"Thursday", "Khaman", "Aloo ke paranthe", "Mutter"},
                {"Friday", "Poha, Jalebi", "Pav Bhaji", "Dosa"},
                {"Saturday", "samosa", "Sabji", "Chawal"},
                {"Sunday", "chowmeeen", "Sambar", null}
            },
            new String [] {
                "Day", "Breakfast", "Lunch", "Dinner"
            }
        ));
        jTable3.setRowHeight(25);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(2).setHeaderValue("Lunch");
            jTable3.getColumnModel().getColumn(3).setHeaderValue("Dinner");
        }

        menuPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 930, 200));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 1030, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMousePressed
        homePanel.setVisible(true);
        studentPanel.setVisible(false);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
        addStudentPanel.setVisible(false);
    }//GEN-LAST:event_homeLabelMousePressed

    private void studentLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMousePressed
        homePanel.setVisible(false);
        studentPanel.setVisible(true);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
                addStudentPanel.setVisible(false);

    }//GEN-LAST:event_studentLabelMousePressed

    private void staffLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLabelMousePressed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        studentPanel.setVisible(false);
        staffPanel.setVisible(true);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
                addStudentPanel.setVisible(false);

    }//GEN-LAST:event_staffLabelMousePressed

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void attendenceLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceLabelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_attendenceLabelMouseReleased

    private void timingLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timingLabelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_timingLabelMouseReleased

    private void accountLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_accountLabelMouseReleased

    private void inventoryLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryLabelMouseReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_inventoryLabelMouseReleased

    private void studentButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentButtonMousePressed

        homePanel.setVisible(false);
        studentPanel.setVisible(true);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
                addStudentPanel.setVisible(false);


    }//GEN-LAST:event_studentButtonMousePressed

    private void inventoryLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryLabelMousePressed
        homePanel.setVisible(false);
        studentPanel.setVisible(false);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(true);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
                addStudentPanel.setVisible(false);

    }//GEN-LAST:event_inventoryLabelMousePressed

    private void attendenceLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceLabelMousePressed
        homePanel.setVisible(false);
        studentPanel.setVisible(false);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(true);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
                addStudentPanel.setVisible(false);

    }//GEN-LAST:event_attendenceLabelMousePressed

    private void timingLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timingLabelMousePressed
        homePanel.setVisible(false);
        studentPanel.setVisible(false);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(true);
        accountPanel.setVisible(false);
        menuPanel.setVisible(false);
                addStudentPanel.setVisible(false);

    }//GEN-LAST:event_timingLabelMousePressed

    private void accountLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMousePressed
        homePanel.setVisible(false);
        studentPanel.setVisible(false);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(true);
        menuPanel.setVisible(false);
                addStudentPanel.setVisible(false);

    }//GEN-LAST:event_accountLabelMousePressed

    private void menuPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPanel1MousePressed

    private void menuPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPanel1MouseReleased

    private void menulabelmousepressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulabelmousepressed
        homePanel.setVisible(false);
        studentPanel.setVisible(false);
        staffPanel.setVisible(false);
        inventoryPanel.setVisible(false);
        attendencePanel.setVisible(false);
        timingsPanel.setVisible(false);
        accountPanel.setVisible(false);
        menuPanel.setVisible(true);
                addStudentPanel.setVisible(false);

    }//GEN-LAST:event_menulabelmousepressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel8MousePressed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void fatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNameActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void collegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeActionPerformed

    private void feestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feestatusActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        studentPanel.setVisible(false);
        addStudentPanel.setVisible(true);
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void addStudentButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentButton1MouseClicked


    }//GEN-LAST:event_addStudentButton1MouseClicked

    private void addStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButton1ActionPerformed
        String getFirstName = fname.getText();
        String getLastName = lname.getText();
        String getFatherName = fatherName.getText();
        String getContact = contact.getText();
        String getAddress = address.getText();
        String getCollege = college.getText();
        String getFeeStatus = feestatus.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Student", "root", "");
            String sql = ("Insert into student (First_Name, Last_name, Father_Name, Contact, Address, College, Fee_status) values(?,?,?,?,?,?,?);");

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, getFirstName);
            ps.setString(2, getLastName);
            ps.setString(3, getFatherName);
            ps.setString(4, getContact);
            ps.setString(5, getAddress);
            ps.setString(6, getCollege);
            ps.setString(7, getFeeStatus);
            Boolean flag = ps.execute();
            if (!flag) {
                System.out.println("Done");
            }

        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_addStudentButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountLabel;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton addStudentButton1;
    private javax.swing.JPanel addStudentPanel;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel attendenceLabel;
    private javax.swing.JPanel attendencePanel;
    private javax.swing.JLabel btn_exit;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private java.awt.Canvas canvas3;
    private java.awt.Canvas canvas4;
    private java.awt.Canvas canvas5;
    private java.awt.Canvas canvas6;
    private java.awt.Canvas canvas7;
    private java.awt.Canvas canvas9;
    private javax.swing.JTextField college;
    private javax.swing.JLabel collegeLabel;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField fatherName;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JLabel feeStatusLabel;
    private javax.swing.JTextField feestatus;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel inventoryLabel;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lname;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel menuPanel1;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel staffLabel;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JLabel studentButton;
    private javax.swing.JPanel studentLabel;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel timingLabel;
    private javax.swing.JPanel timingsPanel;
    // End of variables declaration//GEN-END:variables

    private void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        dateLabel.setText(s.format(d));
    }

    private void showTime() {
        new Timer(00, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timeLabel.setText(s.format(d));
            }
        }).start();
    }
}
